add TDurableKV
free2ex/standart-services pull request #10
Opened 2023-04-28 14:44 UTC by karina-kushnir-free2ex

2023-04-28 15:17 UTC, alexandermartinevski requested changes

2023-04-28 15:17 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    let result = await this.getDurableKVParamWithMetadata(stub, key, cryptoPass);
странный код, а почему так не написать
{value}= await this.getDurableKVParamWithMetadata(stub, key, cryptoPass);
return value

2023-04-29 06:01 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +export interface IDurableKVEnv {}
++

2023-04-29 06:02 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +  private env: IDurableKVEnv;
++

2023-04-29 06:09 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +    const reqBody: { [key: string]: any } = await req.clone().json();
ну давай попробуем без него

2023-04-29 06:10 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +      let request = new Request(`v1/kv/${key}`, this.generateHttpInit("GET"));
++

2023-04-29 06:23 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +      if (!result) {
++

2023-04-29 06:25 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +    let result = await this.getDurableKVParamWithMetadata(stub, key, cryptoPass);
++

2023-04-29 07:27 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +        return await this.handlePostRequest(req);
++

2023-04-29 07:46 UTC, alexandermartinevski requested changes

2023-04-29 07:46 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    let {value} = await this.getDurableKVParamWithMetadata(
С undefined будет так работать?

2023-04-29 07:46 UTC, alexandermartinevski commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
Странно - просто стандартный Env, как в примерах

2023-04-29 07:46 UTC, alexandermartinevski commented on services/TDurableKV.ts
> +    await this.state.storage.delete("all");
Возможно стоит удалить еще alarm

2023-04-29 07:46 UTC, alexandermartinevski commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
Тут приходит другой env, наверное, точно не знаю

2023-04-29 07:49 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +      this.key = stored?.key;
++

2023-04-29 07:49 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +  protected key: string;
++

2023-04-29 07:52 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
так они в примерах тоже сами создают и описывают этот тип

2023-04-29 07:56 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +    await this.state.storage.delete("all");
++

2023-04-29 08:00 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +    let {value} = await this.getDurableKVParamWithMetadata(
не будет(
переписала

2023-04-29 08:05 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +    let {value} = await this.getDurableKVParamWithMetadata(
так, стоп, а мы в этих функциях хотим возвращать только value? 
потому что сейчас я возвращаю объект result: {
          key: string;
          value: string;
          expire?: number;
          meta?: { [key: string]: any };
        }

2023-04-29 08:09 UTC, alexandermartinevski requested changes

2023-04-29 08:09 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    let {value} = await this.getDurableKVParamWithMetadata(
1. getDurableKVParamWithMetadat - возвращает полный json 
 result: {
key: string;
value: string;
expire?: number;
meta?: { [key: string]: any };
}

А getDurableKVParam только value

2023-04-29 08:09 UTC, alexandermartinevski commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
Я тут смотрел
https://github.com/cloudflare/durable-objects-typescript-rollup-esm/blob/master/src/counter.ts

2023-04-29 08:11 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
он у него самой последней строкой описан

2023-04-29 08:13 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
делаю тогда такой export interface IDurableEnv {} ???

2023-04-29 08:52 UTC, alexandermartinevski commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
Давай пока так, а потом лучше поймем и подправим

2023-04-29 09:02 UTC, karina-kushnir-free2ex commented on services/TDurableKV.ts
> +import { IBaseServiceEnv } from "./TBaseService";
++

2023-04-29 09:05 UTC, alexandermartinevski requested changes

2023-04-29 09:05 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    if (!result?.value) {
return result?.value;

2023-04-29 09:05 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    if (!result?.value) {
Что-то мы усложняем

2023-04-29 09:13 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +    if (!result?.value) {
++

2023-04-29 09:24 UTC, merged