change durable obj functions
free2ex/standart-services pull request #16
Opened 2023-07-12 06:23 UTC by karina-kushnir-free2ex

2023-07-12 06:59 UTC, alexandermartinevski requested changes

2023-07-12 06:59 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    DOBinding: DurableObjectNamespace,
Лишнее, посмотри как в getKVParam

2023-07-12 07:29 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +    DOBinding: DurableObjectNamespace,
предлагаешь сделать один общий биндинг?
у нас сейчас это tokenDurableObject

тогда же и валере нужно будет переходить на наш

2023-07-12 15:46 UTC, alexandermartinevski commented on services/TBaseService.ts
> +    DOBinding: DurableObjectNamespace,
Я про использование this для доступа к переменным класса.

2023-07-14 07:05 UTC, karina-kushnir-free2ex commented on services/TBaseService.ts
> +    DOBinding: DurableObjectNamespace,
вернула stub
буду переходить внутри микросервисов на + "env.instance"

2023-07-14 09:17 UTC, merged