add instance & set varsArray
free2ex/standart-services pull request #17
Opened 2023-07-24 13:18 UTC by karina-kushnir-free2ex

2023-07-24 13:42 UTC, alexandermartinevski requested changes

2023-07-24 13:42 UTC, alexandermartinevski commented on services/THttpService.ts
> +  abstract varsArray: Array<string>;
Убрать abstract - тут не нужно такой жесткости

2023-07-24 13:55 UTC, alexandermartinevski commented on services/THttpService.ts
> +  abstract varsArray: Array<string>;
varsEnvArray

2023-07-24 13:59 UTC, alexandermartinevski requested changes

2023-07-24 13:59 UTC, alexandermartinevski commented on services/THttpService.ts
> +        vars[v] = env[v];
Давай через вопрос, чтобы обращение к массиву не падало

2023-07-25 06:08 UTC, karina-kushnir-free2ex commented on services/THttpService.ts
> +  abstract varsArray: Array<string>;
++

2023-07-25 08:23 UTC, alexandermartinevski requested changes

2023-07-25 08:23 UTC, alexandermartinevski commented on services/THttpService.ts
> +  varsEnvArray: Array<string>;
на двух новых переменных protected

2023-07-25 08:23 UTC, alexandermartinevski commented on services/THttpService.ts
>    constructor(env: IHttpServiceEnv, name: string) {
Давай в констуктор кроме имени передавать версию, так похоже лучше.
Не обязательный параметр

2023-07-25 08:24 UTC, alexandermartinevski commented on services/THttpService.ts
>    constructor(env: IHttpServiceEnv, name: string) {
И переменную версию вынести в base класс

2023-07-25 08:25 UTC, alexandermartinevski commented on services/THttpService.ts
>    constructor(env: IHttpServiceEnv, name: string) {
И подправить все конструкторы

2023-07-25 08:52 UTC, karina-kushnir-free2ex commented on services/THttpService.ts
> +  varsEnvArray: Array<string>;
++

2023-07-25 10:57 UTC, merged