add encrypt and decrypt function, test version
free2ex/standart-services pull request #3
Opened 2023-03-27 13:39 UTC by karina-kushnir-free2ex

2023-03-27 17:13 UTC, alexandermartinevski requested changes

2023-03-27 17:13 UTC, alexandermartinevski commented on services/service.ts
> +      let iv = crypto.getRandomValues(new Uint8Array(12));
Код const password = window.prompt("Enter your password");
заменяем на password=cryptoPass

2023-03-27 17:13 UTC, alexandermartinevski commented on services/service.ts
> +        JSON.stringify(encryptedValue),
https://developers.cloudflare.com/workers/runtime-apis/web-standards/
base64 ?

2023-03-27 17:13 UTC, alexandermartinevski commented on services/service.ts
> +        JSON.stringify(encryptedValue),
Я бы эту часть перенес в   if (cryptoKey)
и больше if не нужно

2023-03-28 05:22 UTC, alexandermartinevski commented on services/service.ts
> +        JSON.stringify(encryptedValue),
И давай соберем всю криптографию в отдельные две функции: зашифровать и расшифровать.

2023-03-28 06:29 UTC, karina-kushnir-free2ex commented on services/service.ts
>      kvKey: string,
++

2023-03-28 08:40 UTC, karina-kushnir-free2ex commented on services/service.ts
> +      let iv = crypto.getRandomValues(new Uint8Array(12));
++

2023-03-28 08:40 UTC, karina-kushnir-free2ex commented on services/service.ts
> +        JSON.stringify(encryptedValue),
++

2023-03-29 13:20 UTC, karina-kushnir-free2ex commented on services/service.ts
> +      headers: Object.entries(headers).filter((head) => {
++

2023-03-30 08:19 UTC, alexandermartinevski requested changes

2023-03-30 09:14 UTC, karina-kushnir-free2ex commented on services/service.ts
> +      if (result && result.value) {
++

2023-03-30 09:15 UTC, karina-kushnir-free2ex commented on services/service.ts
> +    if (cryptoPass && result.value && result.metadata && result.metadata.iv) {
++

2023-03-30 09:35 UTC, merged